### PR TITLE
Add centos7 image

### PR DESCRIPTION
**Pull request by thomasboussekey**
Hello @taivokasper ,

I have created a centos image. Its size is 701 MB.
I hoped to perform better, but...

I discovered that omnidb offers also RPM & DEB files for installation: https://omnidb.org/en/downloads-en

I will try to play with soon ;-)

Thomas

### CODE REVIEW

**Comment by thomasboussekey** [comment]
I'm more at ease with RH distros...

Perhap's other people feel the same.

I can understand you didn't want to add it, feel free.

Thomas

Le dim. 28 oct. 2018 à 13:27, Taivo Käsper <notifications@github.com> a
écrit :

**Comment by taivokasper** [comment]
Are you using this docker image as a base image? Or you are more at ease with centos when submitting update pull requests for OmniDB?

I think for a user of this image there is no difference what it runs on. What do you think?

**Comment by thomasboussekey** [comment]
Hi,

As ops, I like to have the possibility to choose the container I want to
install in the Linux distribution, I'm more comfortable with.

I'm not at ease with debian-like linux, because I only use rhel and centos
VMs at work.

Several weeks ago, I had to install oracle linux for testing solution. When
I had to perform network debugging I didn't know how to install wget or
curl, which one was compatible... a nightmare...

For the project, I thought it could be interesting to offer both alpine and
centos compatibility.

Have a nice week
Regards
Thomas

Le dim. 28 oct. 2018 à 14:59, Taivo Käsper <notifications@github.com> a
écrit :

**Comment by thomasboussekey** [comment]
If you prefer,I can update the merge request and put my email address as
maintainer of the image 😉

Tom

**Comment by taivokasper** [comment]
Hi @thomasboussekey,

I tried setting up docker cloud for building, testing and publishing multiple images with different base images but unfortunately then the build times for every PR get too slow (around 30 minutes).

I think for now it is better to keep it on alpine only.

**Pull request closed without merging**
