### PR TITLE
update alpine os from 3.8 to 3.9

### PR DESCRIPTION
**Pull request by thomasboussekey**

### CODE REVIEW

**Comment by taivokasper** [comment]
Thanks, I'll merge and release under tag v2.12.0-alpine_3.9

**Comment by taivokasper** [comment]
@thomasboussekey I will soon release upgrades to OmniDB version as well.

Tag: v2.13.0-alpine_3.9
Tag: v2.14.0-alpine_3.9

**Comment by thomasboussekey** [comment]
Hello @taivokasper ,

Thank you for the merge process.

Yesterday, I also tried to upgrade omnidb to 2.13 or 2.14, but I encountered the following issue:
https://github.com/OmniDB/OmniDB/issues/902

If your container is working fine, there might be a problem on my laptop or somewhere else!

Have a nice week-end,
Regards,
Thomas

**Comment by taivokasper** [comment]
Hi @thomasboussekey,

Tags v2.14.0-alpine_3.9 and v2.13.0-alpine_3.9 both work fine for me. I can log in, connect to a postgresql database, run queries and there are no warnings/errors in console.

Very random but to be on the safe side try using OmniDB without any browser plugins. This can easily be done using incognito mode on chrome or private browsing in firefox. Maybe there is a browser plugin that messes with the token or headers?

Have a good weekend!

**Comment by thomasboussekey** [comment]
Hello @taivokasper ,

You're correct, my new containers are also working fine with omnidb 2.13 and 2.14.
I think my problem was linked to webbrowser cache.

Version 2.15 is expected for this week ;-)

Have a nice week,
Regards,
Thomas

**Pull request merged**
